Repository B-dink/B-dink-Server, pull requests merged in 2025-05, with the labels that each got.

#168 [Feature] Toss payment API 구현
  .DS_Store
  bdink/build.gradle
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/global/exception/model/PaymentFailedException.java
  bdink/src/main/java/com/app/bdink/payment/controller/PaymentController.java
  bdink/src/main/java/com/app/bdink/payment/controller/dto/CancelRequest.java
  bdink/src/main/java/com/app/bdink/payment/controller/dto/PaymentResponse.java
  bdink/src/main/java/com/app/bdink/payment/entity/CardInfo.java
  bdink/src/main/java/com/app/bdink/payment/entity/CashReceipt.java
  bdink/src/main/java/com/app/bdink/payment/entity/CashReceiptHistory.java
  bdink/src/main/java/com/app/bdink/payment/entity/EasyPay.java
  bdink/src/main/java/com/app/bdink/payment/entity/GiftCertificate.java
  bdink/src/main/java/com/app/bdink/payment/entity/MobilePhone.java
  bdink/src/main/java/com/app/bdink/payment/entity/Payment.java
  bdink/src/main/java/com/app/bdink/payment/entity/PaymentCancel.java
  bdink/src/main/java/com/app/bdink/payment/entity/Transfer.java
  bdink/src/main/java/com/app/bdink/payment/entity/VirtualAccount.java
  bdink/src/main/java/com/app/bdink/payment/entity/embedded/CheckoutInfo.java
  bdink/src/main/java/com/app/bdink/payment/entity/embedded/FailureInfo.java
  bdink/src/main/java/com/app/bdink/payment/entity/embedded/ReceiptInfo.java
  bdink/src/main/java/com/app/bdink/payment/entity/embedded/RefundReceiveAccount.java
  bdink/src/main/java/com/app/bdink/payment/service/PaymentService.java
  bdink/src/test/java/com/app/bdink/classroom/domain/PriceDetailTest.java
Labels: Feature

#173 [Feature] 클래스룸 Detail Image 생성
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/request/ClassRoomImageCreateRequest.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomImageResponse.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomDetailImage.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ClassRoomDetailImageRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomDetailPageImageService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/classroom/service/command/CreateClassRoomCommand.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
Labels: Feature

#178 [Modify] Career의 강사 조회 api 강사 프로필이미지 추가
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/AllClassRoomResponse.java
Labels: modify

#175 [Refactor] 콜러스 미디어와 기존 api 연결, 콜러스 미디어 학습 시청기록 api 생성
  bdink/src/main/java/com/app/bdink/chapter/repository/ChapterRepository.java
  bdink/src/main/java/com/app/bdink/chapter/service/ChapterService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMedia.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/UserKeyRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
Labels: Feature, modify

#180 [Feature] 유튜브 비디오 CRUD
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/youtube/controller/YoutubeController.java
  bdink/src/main/java/com/app/bdink/youtube/domain/YoutubeInfoDto.java
  bdink/src/main/java/com/app/bdink/youtube/entity/Youtube.java
  bdink/src/main/java/com/app/bdink/youtube/repository/YoutubeRepository.java
  bdink/src/main/java/com/app/bdink/youtube/service/YoutubeService.java
Labels: Feature

#183 [Feature] YoutubeVideo 유튜브 타입 조회 API
  bdink/src/main/java/com/app/bdink/youtube/controller/YoutubeController.java
  bdink/src/main/java/com/app/bdink/youtube/domain/YoutubeInfoDto.java
  bdink/src/main/java/com/app/bdink/youtube/domain/YoutubeType.java
  bdink/src/main/java/com/app/bdink/youtube/entity/Youtube.java
  bdink/src/main/java/com/app/bdink/youtube/repository/YoutubeRepository.java
  bdink/src/main/java/com/app/bdink/youtube/service/YoutubeService.java
Labels: Feature

#185 [Feature] Kollus 진행률 콜백 api 구현, 수강 엔티티를 통한 진행률 기능 개발, 클래스룸 디테일 페이지 결제 관련 데이터 추가
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
  bdink/src/main/java/com/app/bdink/classroom/port/in/ClassRoomUseCase.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/PlayRequestDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
  bdink/src/main/java/com/app/bdink/sugang/controller/SugangController.java
  bdink/src/main/java/com/app/bdink/sugang/controller/dto/SugangStatus.java
  bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangClassRoomInfo.java
  bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangInfoDto.java
  bdink/src/main/java/com/app/bdink/sugang/entity/Sugang.java
  bdink/src/main/java/com/app/bdink/sugang/repository/SugangRepository.java
  bdink/src/main/java/com/app/bdink/sugang/service/SugangService.java
  bdink/src/main/java/com/app/bdink/youtube/service/YoutubeService.java
Labels: Feature

#189 modify/#188(SugangController) 수강신청 클래스룸 목록 조회 api 응답값 변경
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/sugang/controller/SugangController.java
Labels: modify

#201 [Modify] 인증번호 체크 api 3분 이상 시간 소요시 인증 되는 버그 수정
  bdink/src/main/java/com/app/bdink/external/coolsms/entity/PhoneVerify.java
  bdink/src/main/java/com/app/bdink/external/coolsms/service/SmsService.java
Labels: modify

#203 [Add] deleteBookmarkByClassRoomId API 구현
  bdink/src/main/java/com/app/bdink/bookmark/adapter/in/controller/BookmarkController.java
  bdink/src/main/java/com/app/bdink/bookmark/repository/BookmarkRepository.java
  bdink/src/main/java/com/app/bdink/bookmark/service/BookmarkService.java
  bdink/src/main/java/com/app/bdink/review/adapter/in/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/review/service/ReviewService.java
Labels: enhancement

#220 [Feature] 콜러스 재생 콜백 api 생성, 마이페이지 api 생성
  bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/LmsRequestDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/PlayRequestDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/instructor/repository/InstructorRepository.java
  bdink/src/main/java/com/app/bdink/mypage/controller/MyPageController.java
  bdink/src/main/java/com/app/bdink/mypage/dto/response/MyPageResponse.java
  bdink/src/main/java/com/app/bdink/mypage/service/MyPageService.java
Labels: Feature

#235 [Modify] Sugang all api 해당 강의 강사 이름 응답 추가, MyPage API 닉네임 응답 추가
  bdink/src/main/java/com/app/bdink/mypage/dto/response/MyPageResponse.java
  bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangClassRoomInfo.java
Labels: modify

#240 [BugFix] Kollus play callback API kind 값 분기처리
  bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
Labels: bug

#245 [Modify] 앱단 개발 질문 관련 응답 값 수정
  bdink/src/main/java/com/app/bdink/oauth2/controller/SocialAuthController.java
  bdink/src/main/java/com/app/bdink/sugang/controller/SugangController.java
Labels: modify

#253 [Modify] 북마크 관련 API 수정 사항 반영
  bdink/src/main/java/com/app/bdink/bookmark/adapter/in/controller/dto/response/BookmarkResponse.java
  bdink/src/main/java/com/app/bdink/bookmark/repository/BookmarkRepository.java
  bdink/src/main/java/com/app/bdink/bookmark/service/BookmarkService.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
Labels: modify

#255 [Modify] 소셜 로그인 성공시 응답 코드 변경
  bdink/src/main/java/com/app/bdink/oauth2/apple/service/AppleSignInService.java
  bdink/src/main/java/com/app/bdink/oauth2/kakao/service/KakaoSignInService.java
Labels: modify

#257 [Add] 클래스룸 챕터 조회 API 진행률 관련 응답추가
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ChapterListResponse.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ChapterResponse.java
  bdink/src/main/java/com/app/bdink/classroom/port/in/ClassRoomUseCase.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
  bdink/src/main/java/com/app/bdink/lecture/controller/dto/response/LectureResponse.java
  bdink/src/main/java/com/app/bdink/sugang/entity/Sugang.java
Labels: enhancement

#267 [Modify] 클래스룸 챕터 조회 api 500 에러 자세한 에러 처리 추가
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
Labels: modify

#274 [Modify] 클래스룸 디테일 페이지 조회 API에 응답 데이터 추가, 챕터마다 썸네일 페이지 데이터 추가
  bdink/src/main/java/com/app/bdink/chapter/controller/ChapterController.java
  bdink/src/main/java/com/app/bdink/chapter/entity/Chapter.java
  bdink/src/main/java/com/app/bdink/chapter/service/ChapterService.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailChapterResponse.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/lecture/controller/dto/response/LectureDetailResponse.java
  bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
Labels: modify

#277 [Modify] 수강 ALL API에 강의 데이터 추가, Kollus url 발급 api에 강사명, 강의명 데이터 추가
  bdink/src/main/java/com/app/bdink/chapter/controller/ChapterController.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/response/KollusApiResponse.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
  bdink/src/main/java/com/app/bdink/sugang/controller/dto/response/SugangClassRoomInfo.java
  bdink/src/main/java/com/app/bdink/sugang/entity/Sugang.java
  bdink/src/main/java/com/app/bdink/sugang/service/SugangService.java
Labels: modify

#288 [Hotfix] 토큰 재발급 API 500 에러 해결
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/token/TokenProvider.java
  bdink/src/main/java/com/app/bdink/oauth2/controller/SocialAuthController.java
  bdink/src/main/java/com/app/bdink/oauth2/domain/RefreshToken.java
Labels: bug

#290 [Modify] Kollus url 발급 API 이전, 다음 강의 정보 추가
  bdink/src/main/java/com/app/bdink/external/kollus/dto/response/KollusApiResponse.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
Labels: modify
