Repository B-dink/B-dink-Server, pull requests merged in 2025-04, with the labels that each got.

#101 feature/#94(Sugang): 진행률 관련 로직 작성
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomProgressResponse.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
  bdink/src/main/java/com/app/bdink/sugang/entity/Sugang.java
  bdink/src/main/java/com/app/bdink/sugang/repository/SugangRepository.java
Labels: Feature

#112 feature/#111(Instructor): 강사 홍보 기능 구현
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/InstructorDto.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/request/UpdateInstructorDto.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/response/InstructorInfoDto.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/out/persistence/entity/Instructor.java
  bdink/src/main/java/com/app/bdink/instructor/domain/InstructorDomain.java
  bdink/src/main/java/com/app/bdink/instructor/mapper/InstructorMapper.java
  bdink/src/main/java/com/app/bdink/instructor/service/InstructorService.java
Labels: Feature

#124 [feature#123] 신고하기 구현
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/qna/service/QuestionService.java
  bdink/src/main/java/com/app/bdink/report/controller/ReportController.java
  bdink/src/main/java/com/app/bdink/report/controller/dto/request/ReportDto.java
  bdink/src/main/java/com/app/bdink/report/controller/dto/response/ReportResponse.java
  bdink/src/main/java/com/app/bdink/report/domain/ReportCase.java
  bdink/src/main/java/com/app/bdink/report/domain/ReportReason.java
  bdink/src/main/java/com/app/bdink/report/entity/Report.java
  bdink/src/main/java/com/app/bdink/report/repository/ReportRepository.java
  bdink/src/main/java/com/app/bdink/report/service/ReportService.java
Labels: Feature

#125 Develop
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/qna/service/QuestionService.java
  bdink/src/main/java/com/app/bdink/report/controller/ReportController.java
  bdink/src/main/java/com/app/bdink/report/controller/dto/request/ReportDto.java
  bdink/src/main/java/com/app/bdink/report/controller/dto/response/ReportResponse.java
  bdink/src/main/java/com/app/bdink/report/domain/ReportCase.java
  bdink/src/main/java/com/app/bdink/report/domain/ReportReason.java
  bdink/src/main/java/com/app/bdink/report/entity/Report.java
  bdink/src/main/java/com/app/bdink/report/repository/ReportRepository.java
  bdink/src/main/java/com/app/bdink/report/service/ReportService.java
Labels: modify

#128 feature/#126(Schedule): 스케줄 관련 구현
  bdink/src/main/java/com/app/bdink/schedule/controller/ScheduleController.java
  bdink/src/main/java/com/app/bdink/schedule/controller/dto/request/ScheduleRequest.java
  bdink/src/main/java/com/app/bdink/schedule/controller/dto/response/ScheduleResponse.java
  bdink/src/main/java/com/app/bdink/schedule/domain/CompetitionType.java
  bdink/src/main/java/com/app/bdink/schedule/entity/Schedule.java
  bdink/src/main/java/com/app/bdink/schedule/repository/ScheduleRepository.java
  bdink/src/main/java/com/app/bdink/schedule/service/ScheduleService.java
Labels: modify

#135 refactor/#130(MemberRequestDto): name validation 추가
  bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberRequestDto.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberSocialRequestDto.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberUpdateDto.java
  bdink/src/main/java/com/app/bdink/oauth2/controller/SocialAuthController.java
Labels: modify

#151 refactor/#147(SocialAuthController): 문자 인증 번호 체크 api 분기처리
  bdink/src/main/java/com/app/bdink/external/coolsms/service/SmsService.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/oauth2/controller/SocialAuthController.java
Labels: modify

#152 Feature/#144(Kollus) : Kollus Media 관련 api 구현
  bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/KollusMediaType.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/KollusTokenDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/UserKeyDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/DeleteRequestDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/PlayRequestDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/request/callback/UploadRequestDTO.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/response/CallbackResponse.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/response/KollusApiResponse.java
  bdink/src/main/java/com/app/bdink/external/kollus/dto/response/KollusResponse.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMedia.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/UserKey.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/UserKeyRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/global/token/JsonUtil.java
  bdink/src/main/java/com/app/bdink/global/token/KollusTokenProvider.java
  bdink/src/main/java/com/app/bdink/global/token/TokenProvider.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/member/entity/Member.java
  bdink/src/main/java/com/app/bdink/member/repository/MemberRepository.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
  bdink/src/main/java/com/app/bdink/oauth2/domain/TokenDto.java
  bdink/src/test/java/com/app/bdink/global/token/TokenProviderTest.java
Labels: Feature

#156 hotfix/#155(KollusService): kollus 업로드 콜백 로직 수정
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
Labels: bug
