Repository B-dink/B-dink-Server, pull requests merged in 2025-06, with the labels that each got.

#293 [Modify] version check-update api 토큰 검증에서 제외
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
Labels: modify

#294 push Develop to Main
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
Labels: modify

#304 [Fix] 애플 인앱 결제 복원을 대비한 구현부 수정
  bdink/src/main/java/com/app/bdink/payment/apple/entity/ApplePurchaseHistory.java
  bdink/src/main/java/com/app/bdink/payment/apple/repository/ApplePurchaseHistoryRepository.java
  bdink/src/main/java/com/app/bdink/payment/apple/service/ApplePaymentServiceImpl.java
Labels: modify

#311 [Hotfix] WIDGET_SECRET_KEY 값 수정
  bdink/src/main/java/com/app/bdink/payment/toss/service/PaymentService.java
Labels: bug

#316 [Fix] 결제 취소 후 수강 상태가 변경되지 않는 버그 해결
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/payment/apple/service/ApplePaymentServiceImpl.java
  bdink/src/main/java/com/app/bdink/payment/toss/controller/PaymentController.java
  bdink/src/main/java/com/app/bdink/payment/toss/controller/dto/CancelRequest.java
  bdink/src/main/java/com/app/bdink/payment/toss/service/PaymentService.java
  bdink/src/main/java/com/app/bdink/payment/toss/service/TransactionalPaymentService.java
  bdink/src/main/java/com/app/bdink/payment/transactional/PaymentTransactionalService.java
  bdink/src/main/java/com/app/bdink/payment/transactional/PaymentTransactionalServiceImpl.java
  bdink/src/main/java/com/app/bdink/sugang/service/SugangService.java
Labels: bug

#319 [Feat] 모든 강사 정보 API 추가
  bdink/src/main/java/com/app/bdink/classroom/repository/ClassRoomRepository.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/response/InstructorAllInfoDto.java
  bdink/src/main/java/com/app/bdink/instructor/repository/InstructorRepository.java
  bdink/src/main/java/com/app/bdink/instructor/service/InstructorService.java
Labels: enhancement

#323 [Hotfix] 강사별 클래스룸을 조회 API
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/InstructorController.java
  bdink/src/main/java/com/app/bdink/instructor/adapter/in/controller/dto/response/InstructorClassroomDto.java
Labels: bug

#328 [Modify] 콜러스 MediaLink API 분기처리
  bdink/src/main/java/com/app/bdink/external/kollus/controller/KollusController.java
  bdink/src/main/java/com/app/bdink/external/kollus/entity/KollusMediaLink.java
  bdink/src/main/java/com/app/bdink/external/kollus/repository/KollusMediaLinkRepository.java
  bdink/src/main/java/com/app/bdink/external/kollus/service/KollusService.java
Labels: modify

#333 [Fix] appleProduct canParchase 수정
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/payment/apple/entity/AppleProduct.java
  bdink/src/main/java/com/app/bdink/payment/apple/repository/AppleProductRepository.java
  bdink/src/main/java/com/app/bdink/payment/apple/repository/ApplePurchaseHistoryRepository.java
  bdink/src/main/java/com/app/bdink/payment/apple/service/ApplePaymentServiceImpl.java
Labels: modify

#345 [Feature] ClassRoom Career PROMOTION과 다른 CAREER 분기처리
  bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ClassRoomRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
Labels: enhancement
