Repository B-dink/B-dink-Server, pull requests merged in 2025-03, with the labels that each got.

#28 feature/#23(MemberService): 자체 로그인 작성
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
  bdink/src/main/java/com/app/bdink/global/template/RspTemplate.java
  bdink/src/main/java/com/app/bdink/member/controller/MemberController.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberRequestDto.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/response/MemberLoginResponseDto.java
  bdink/src/main/java/com/app/bdink/member/entity/Member.java
  bdink/src/main/java/com/app/bdink/member/exception/InvalidMemberException.java
  bdink/src/main/java/com/app/bdink/member/exception/NotFoundMemberException.java
  bdink/src/main/java/com/app/bdink/member/repository/MemberRepository.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
Labels: Feature

#29 refactor/#24(Schedule): 뉴스 -> 일정 변경
  bdink/src/main/java/com/app/bdink/news/controller/NewsController.java
  bdink/src/main/java/com/app/bdink/news/controller/dto/request/NewsReqDto.java
  bdink/src/main/java/com/app/bdink/news/controller/dto/response/NewsResDto.java
  bdink/src/main/java/com/app/bdink/news/entity/News.java
  bdink/src/main/java/com/app/bdink/news/repository/NewsRepository.java
  bdink/src/main/java/com/app/bdink/news/service/NewsService.java
  bdink/src/main/java/com/app/bdink/schedule/controller/ScheduleController.java
  bdink/src/main/java/com/app/bdink/schedule/controller/dto/request/ScheduleRequest.java
  bdink/src/main/java/com/app/bdink/schedule/controller/dto/response/ScheduleResponse.java
  bdink/src/main/java/com/app/bdink/schedule/domain/ScheduleType.java
  bdink/src/main/java/com/app/bdink/schedule/entity/Schedule.java
  bdink/src/main/java/com/app/bdink/schedule/repository/ScheduleRepository.java
  bdink/src/main/java/com/app/bdink/schedule/service/ScheduleService.java
Labels: Feature

#36 Feature/#32
  bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/entity/ClassRoom.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/controller/LambdaController.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/controller/request/CdnLinkUrlDto.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/domain/Media.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/repository/MediaRepository.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/service/MediaService.java
  bdink/src/main/java/com/app/bdink/external/aws/service/S3Service.java
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/dto/LectureDto.java
  bdink/src/main/java/com/app/bdink/lecture/controller/dto/response/LectureInfo.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
Labels: Feature

#37 lambda test를 위해 머지
  bdink/build.gradle
  bdink/src/main/java/com/app/bdink/classroom/controller/BookmarkController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/request/ClassRoomDto.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/request/ReviewRequest.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/BookmarkResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ReviewResponse.java
  bdink/src/main/java/com/app/bdink/classroom/domain/Review.java
  bdink/src/main/java/com/app/bdink/classroom/entity/Bookmark.java
  bdink/src/main/java/com/app/bdink/classroom/entity/ClassRoom.java
  bdink/src/main/java/com/app/bdink/classroom/repository/BookmarkRepository.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ReviewRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/BookmarkService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ReviewService.java
  bdink/src/main/java/com/app/bdink/external/aws/S3Config.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/controller/LambdaController.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/controller/request/CdnLinkUrlDto.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/domain/Media.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/repository/MediaRepository.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/service/MediaService.java
  bdink/src/main/java/com/app/bdink/external/aws/service/S3Service.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/SmsController.java
  bdink/src/main/java/com/app/bdink/external/coolsms/dto/request/SmsSendRequest.java
  bdink/src/main/java/com/app/bdink/external/coolsms/entity/VerifyUser.java
  bdink/src/main/java/com/app/bdink/external/coolsms/service/SmsService.java
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
  bdink/src/main/java/com/app/bdink/global/template/RspTemplate.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/dto/LectureDto.java
  bdink/src/main/java/com/app/bdink/lecture/controller/dto/response/LectureInfo.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
  bdink/src/main/java/com/app/bdink/member/controller/MemberController.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberRequestDto.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/response/MemberLoginResponseDto.java
  bdink/src/main/java/com/app/bdink/member/entity/Member.java
  bdink/src/main/java/com/app/bdink/member/exception/InvalidMemberException.java
  bdink/src/main/java/com/app/bdink/member/exception/NotFoundMemberException.java
  bdink/src/main/java/com/app/bdink/member/repository/MemberRepository.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
  bdink/src/main/java/com/app/bdink/news/controller/NewsController.java
  bdink/src/main/java/com/app/bdink/news/controller/dto/request/NewsReqDto.java
  bdink/src/main/java/com/app/bdink/news/controller/dto/response/NewsResDto.java
  bdink/src/main/java/com/app/bdink/news/entity/News.java
  bdink/src/main/java/com/app/bdink/news/repository/NewsRepository.java
  bdink/src/main/java/com/app/bdink/news/service/NewsService.java
  bdink/src/main/java/com/app/bdink/schedule/controller/ScheduleController.java
  bdink/src/main/java/com/app/bdink/schedule/controller/dto/request/ScheduleRequest.java
  bdink/src/main/java/com/app/bdink/schedule/controller/dto/response/ScheduleResponse.java
  bdink/src/main/java/com/app/bdink/schedule/domain/ScheduleType.java
  bdink/src/main/java/com/app/bdink/schedule/entity/Schedule.java
  bdink/src/main/java/com/app/bdink/schedule/repository/ScheduleRepository.java
  bdink/src/main/java/com/app/bdink/schedule/service/ScheduleService.java
Labels: Feature

#40 Feature/#32
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/controller/LambdaController.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/controller/request/CdnLinkUrlDto.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/service/MediaService.java
  bdink/src/main/java/com/app/bdink/external/aws/service/S3Service.java
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
Labels: Feature

#57 [Modify/#43] 남은 API들 로그인 연동
  bdink/src/main/java/com/app/bdink/classroom/controller/BookmarkController.java
  bdink/src/main/java/com/app/bdink/classroom/domain/Career.java
  bdink/src/main/java/com/app/bdink/common/util/MemberUtilService.java
  bdink/src/main/java/com/app/bdink/global/config/SwaggerConfig.java
  bdink/src/main/java/com/app/bdink/lecture/controller/InstructorController.java
Labels: modify

#65 feature/#64(ReviewController): 리뷰 페이지네이션 기능 추가
  bdink/src/main/java/com/app/bdink/classroom/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ReviewRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/ReviewService.java
Labels: Feature

#68 feature/#66(ClassRoom): 클래스 디테일 페이지 조회 api 작성
  bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/repository/BookmarkRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/BookmarkService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
Labels: Feature

#69 feature/#67(ClassRoomController): 클래스룸 정보 조회 api 추가
  bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ChapterResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomSummeryDto.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/LectureResponse.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Chapter.java
  bdink/src/main/java/com/app/bdink/lecture/repository/ChapterRepository.java
  bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
Labels: Feature

#70 Develop
  bdink/src/main/java/com/app/bdink/classroom/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/AllClassRoomResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ChapterResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomResponse.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/ClassRoomSummeryDto.java
  bdink/src/main/java/com/app/bdink/classroom/controller/dto/response/LectureResponse.java
  bdink/src/main/java/com/app/bdink/classroom/repository/BookmarkRepository.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ClassRoomRepository.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ReviewRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/BookmarkService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ReviewService.java
  bdink/src/main/java/com/app/bdink/classroom/util/InstructorUtilService.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/SmsController.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/dto/PhoneRequest.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/dto/PhoneResponse.java
  bdink/src/main/java/com/app/bdink/external/coolsms/entity/PhoneVerify.java
  bdink/src/main/java/com/app/bdink/external/coolsms/entity/VerifyUser.java
  bdink/src/main/java/com/app/bdink/external/coolsms/repository/PhoneRepository.java
  bdink/src/main/java/com/app/bdink/external/coolsms/service/SmsService.java
  bdink/src/main/java/com/app/bdink/global/config/SecurityConfig.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Chapter.java
  bdink/src/main/java/com/app/bdink/lecture/repository/ChapterRepository.java
  bdink/src/main/java/com/app/bdink/lecture/repository/LectureRepository.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
  bdink/src/main/java/com/app/bdink/member/entity/Member.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
  bdink/src/main/java/com/app/bdink/nutrient/controller/NutrientController.java
  bdink/src/main/java/com/app/bdink/nutrient/controller/dto/request/NutrientReqDto.java
  bdink/src/main/java/com/app/bdink/nutrient/controller/dto/response/NutrientResDto.java
  bdink/src/main/java/com/app/bdink/nutrient/entity/Nutrient.java
  bdink/src/main/java/com/app/bdink/nutrient/repository/NutrientRepository.java
  bdink/src/main/java/com/app/bdink/nutrient/service/NutrientService.java
  bdink/src/main/java/com/app/bdink/qna/controller/AnswerController.java
  bdink/src/main/java/com/app/bdink/qna/controller/QuestionController.java
  bdink/src/main/java/com/app/bdink/qna/controller/dto/request/QnARequest.java
  bdink/src/main/java/com/app/bdink/qna/controller/dto/response/AnswerDto.java
  bdink/src/main/java/com/app/bdink/qna/controller/dto/response/QnAResponse.java
  bdink/src/main/java/com/app/bdink/qna/controller/dto/response/QuestionResponse.java
  bdink/src/main/java/com/app/bdink/qna/entity/Answer.java
  bdink/src/main/java/com/app/bdink/qna/entity/Question.java
  bdink/src/main/java/com/app/bdink/qna/repository/AnswerRepository.java
  bdink/src/main/java/com/app/bdink/qna/repository/QuestionRepository.java
  bdink/src/main/java/com/app/bdink/qna/service/AnswerService.java
  bdink/src/main/java/com/app/bdink/qna/service/QuestionService.java
Labels: Feature

#71 Feature/#63
  bdink/src/main/java/com/app/bdink/classroom/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/classroom/domain/ChapterSummary.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/classroom/util/InstructorUtilService.java
  bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Chapter.java
  bdink/src/main/java/com/app/bdink/lecture/entity/Lecture.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
Labels: Feature

#76 Refactor/#75
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/BookmarkController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/common/util/CreateIdDto.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/SmsController.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/dto/VerifyResponse.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/global/oauth2/SocialAuthController.java
  bdink/src/main/java/com/app/bdink/global/oauth2/domain/DoubleCheckResponse.java
  bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/InstructorController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
Labels: modify

#77 Develop
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/BookmarkController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/common/util/CreateIdDto.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/SmsController.java
  bdink/src/main/java/com/app/bdink/external/coolsms/controller/dto/VerifyResponse.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/global/oauth2/SocialAuthController.java
  bdink/src/main/java/com/app/bdink/global/oauth2/domain/DoubleCheckResponse.java
  bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/InstructorController.java
  bdink/src/main/java/com/app/bdink/lecture/controller/LectureController.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
Labels: modify

#80 Refactor/#75
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/qna/controller/AnswerController.java
  bdink/src/main/java/com/app/bdink/qna/controller/QuestionController.java
  bdink/src/main/java/com/app/bdink/schedule/controller/ScheduleController.java
Labels: modify

#83 hotfix(InstructorUtilService)/#82: 권한 판단 에러 수정
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/util/InstructorUtilService.java
  bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
Labels: bug

#84 Feature/#82
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ClassRoomController.java
  bdink/src/main/java/com/app/bdink/classroom/util/InstructorUtilService.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/config/S3Config.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/S3MultipartController.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3PreSignedUrlDto.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3UploadCompleteDto.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3UploadDto.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3UploadInitiateDto.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3UploadPartsDetailDto.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3UploadResultDto.java
  bdink/src/main/java/com/app/bdink/external/aws/s3/controller/dto/S3UploadSignedUrlDto.java
  bdink/src/main/java/com/app/bdink/external/aws/service/S3MultipartService.java
  bdink/src/main/java/com/app/bdink/external/aws/service/S3Service.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/lecture/controller/ChapterController.java
Labels: modify

#89 modify/#85(Error): validation 추가
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/BookmarkController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
  bdink/src/main/java/com/app/bdink/classroom/repository/BookmarkRepository.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ReviewRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/BookmarkService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ReviewService.java
  bdink/src/main/java/com/app/bdink/external/aws/lambda/service/MediaService.java
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/lecture/service/ChapterService.java
  bdink/src/main/java/com/app/bdink/lecture/service/InstructorService.java
  bdink/src/main/java/com/app/bdink/lecture/service/LectureService.java
  bdink/src/main/java/com/app/bdink/qna/controller/QuestionController.java
  bdink/src/main/java/com/app/bdink/qna/entity/Question.java
  bdink/src/main/java/com/app/bdink/qna/service/QuestionService.java
  bdink/src/main/java/com/app/bdink/schedule/controller/ScheduleController.java
  bdink/src/main/java/com/app/bdink/schedule/service/ScheduleService.java
Labels: modify

#91 feature/#86(ClassRoom): 난이도, 리뷰 개수 추가
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/ReviewController.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/request/ClassRoomDto.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/in/controller/dto/response/ClassRoomDetailResponse.java
  bdink/src/main/java/com/app/bdink/classroom/adapter/out/persistence/entity/ClassRoomEntity.java
  bdink/src/main/java/com/app/bdink/classroom/domain/ClassRoom.java
  bdink/src/main/java/com/app/bdink/classroom/domain/Level.java
  bdink/src/main/java/com/app/bdink/classroom/mapper/ClassRoomMapper.java
  bdink/src/main/java/com/app/bdink/classroom/repository/ReviewRepository.java
  bdink/src/main/java/com/app/bdink/classroom/service/ClassRoomService.java
  bdink/src/main/java/com/app/bdink/classroom/service/ReviewService.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
Labels: Feature

#92 [Feature/#82] 소셜 로그인 및 회원탈퇴 구현.
  bdink/.gitignore
  bdink/src/main/java/com/app/bdink/global/exception/Error.java
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/global/oauth2/AuthService.java
  bdink/src/main/java/com/app/bdink/global/oauth2/SocialAuthController.java
  bdink/src/main/java/com/app/bdink/global/oauth2/apple/request/Parts.java
  bdink/src/main/java/com/app/bdink/global/oauth2/apple/request/RevokeParts.java
  bdink/src/main/java/com/app/bdink/global/oauth2/apple/response/TokenResponse.java
  bdink/src/main/java/com/app/bdink/global/oauth2/apple/service/AppleSignInService.java
  bdink/src/main/java/com/app/bdink/global/oauth2/apple/verify/PublicKeyGenerator.java
  bdink/src/main/java/com/app/bdink/global/oauth2/kakao/service/KakaoSignInService.java
  bdink/src/main/java/com/app/bdink/member/entity/Member.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
Labels: Feature

#100 Develop
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/member/controller/MemberController.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/request/MemberMarketingDto.java
  bdink/src/main/java/com/app/bdink/member/controller/dto/response/SocialTypeDto.java
  bdink/src/main/java/com/app/bdink/member/entity/Member.java
  bdink/src/main/java/com/app/bdink/member/service/MemberService.java
Labels: Feature

#98 refactor/#93(PamentConfirmResponse): 결제 정보 추가
  bdink/src/main/java/com/app/bdink/global/exception/Success.java
  bdink/src/main/java/com/app/bdink/payment/ConfirmRequest.java
  bdink/src/main/java/com/app/bdink/payment/PaymentController.java
  bdink/src/main/java/com/app/bdink/payment/PaymentService.java
  bdink/src/main/java/com/app/bdink/payment/domain/Card.java
  bdink/src/main/java/com/app/bdink/payment/domain/EasyPay.java
  bdink/src/main/java/com/app/bdink/payment/domain/PaymentConfirmResponse.java
Labels: modify
